### ISSUE TITLE
When calculating for us-east-1 the box usage type does not have a hyphen before, this causes no rate to be found

### ISSUE THREAD

**Issue by paulsewardasc** [aws-samples/savings-plan-commitment-calculator#1]
[-] eu-west-1, EU-BoxUsage:t3.medium
[-] us-east-1, BoxUsage:t3.medium

Can lines, 74, 78 and 82 of core be fixed to allow for us-east-1?

**Comment by Martini07** [comment]
Hi @paulsewardasc, thanks for reporting. I've pushed a [change](https://github.com/aws-samples/savings-plan-commitment-calculator/commit/867ad791a077bca4f7d82f6cfce36400b9e62327) that should fix the issue.
