### ISSUE TITLE
should it mention that it does not consider lamba and fargate?

### ISSUE THREAD

**Issue by davidecoccia** [aws-samples/savings-plan-commitment-calculator#2]
I was trying to use it to calculate the commitment for a compute savings plan and i realised that the tool is not considering lambda/fargate usage. Shouldn't it mention that?

**Comment by Martini07** [comment]
Hi @davidecoccia, thanks for reporting. I've pushed a [change](https://github.com/aws-samples/savings-plan-commitment-calculator/commit/fcdcb7b85c58f4b4c4a7263686117c73370a1a77) to clarify this point in the README.
