### ISSUE TITLE
possibility of specifying one's own commitment

### ISSUE THREAD

**Issue by dsamazfr** [aws-samples/savings-plan-commitment-calculator#3]
Hello. 
Is there any possibility of adding my own commitment which is lower than the recommendation and then have the calcaulated data?

**Comment by Martini07** [comment]
Hello @dsamazfr, thanks for reaching out.
I would like to know more about your request, can you please provide an example of your use case?

**Comment by Martini07** [comment]
We have not heard back from you regarding this issue in the last 30 days. We hope this means you have resolved your issue or question. If you need continued support, please reopen the issue.
